CREATE TABLE ware (
  sku_id INT AUTO_INCREMENT PRIMARY KEY,
  ean VARCHAR(32) NOT NULL,
  name VARCHAR(255),
  preis DECIMAL(10,2),
  lagerort VARCHAR(64),
  status TINYINT(1) DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

